### ISSUE TITLE
Movement

### ISSUE THREAD

**Issue by trueberryless** [TooMuchBrainProjects/ShadowIsYourFriend#1]
All problems with movement here:

1. player can jump **infinite** (state changes between jump and fall buggy) by **holding** up
2. player _cannot_ jump when standing close to edge (physically not touching edge, but still standing...)

---

Problem 1:
As you can see (yellow), the player's position is nearly 0:

<img src="https://user-images.githubusercontent.com/99918022/168895165-ef626c55-1fbd-4d9f-944f-ec88d4d43c9e.png" alt="Markdown Monster icon" width="300" />

If you hold UP for a while, the player's vertical position (y) is over 50, which should be impossible:

<img src="https://user-images.githubusercontent.com/99918022/168895194-eb5c9d3c-c91f-431b-bbec-9a4c468f01de.png" alt="Markdown Monster icon" width="300" />

---

Problem 2:

You can't see it, but the player stands still but cannot jump...

<img src="https://user-images.githubusercontent.com/99918022/168894678-bc29262b-92b4-4417-a2d3-58c430f47de8.png" alt="Markdown Monster icon" width="300" />

**Comment by clemensschlipfinger** [comment]
Fixed it!
Reason: When entering the states their attributes like IsGrounded are not reseted.
