### ISSUE TITLE
Security cams

### ISSUE THREAD

**Issue by Y0Ying** [TooMuchBrainProjects/ShadowIsYourFriend#14]
The security cams don't have their full light range sometimes. Also this is weird
![Screenshot 2022-06-14 083645](https://user-images.githubusercontent.com/106141484/173509700-3eea0090-3488-4249-b5ca-cc87586430d5.jpg)

**Comment by trueberryless** [comment]
The edge is in the way.

**Comment by trueberryless** [comment]
Also, there are two cameras.
